name: Download and Push LibreOffice Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y wget tar dpkg

      - name: Get Latest LibreOffice Version
        run: |
          LATEST_VERSION=$(wget -qO- "https://download.documentfoundation.org/libreoffice/stable/" | grep -oP 'href="\K[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -1)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Download LibreOffice Binary
        run: |
          wget "https://download.documentfoundation.org/libreoffice/stable/${{ env.LATEST_VERSION }}/deb/x86_64/LibreOffice_${{ env.LATEST_VERSION }}_Linux_x86-64_deb.tar.gz" -O libreoffice.tar.gz

      - name: Extract LibreOffice
        run: |
          mkdir libreoffice
          tar -xvzf libreoffice.tar.gz -C libreoffice --strip-components=1

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
      - name: Commit and Push LibreOffice Binary Files
        run: |
          for file in libreoffice/DEBS/*.deb; do
            git add "$file"
            git commit -m "Added LibreOffice binary file: $(basename "$file")"
            git push origin main
          done

