name: Install LibreOffice on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  install-libreoffice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Package List
        run: sudo apt update

      - name: Install LibreOffice
        run: sudo apt install -y libreoffice

      - name: Verify LibreOffice Installation
        run: libreoffice --version
